FROM openjdk:17-jdk-slim
VOLUME /tmp

# Install dependencies, Chromium, and ChromeDriver
RUN apt-get update && \
    apt-get install -y wget unzip gnupg curl chromium && \
    CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
    rm /tmp/chromedriver.zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose the port to access the application
EXPOSE 8080

# Set environment variables for Chrome
ENV DISPLAY=:99
ENV CHROME_BIN=/usr/bin/google-chrome
ENV CHROME_DRIVER=/usr/local/bin/chromedriver

COPY ../target/news-aggregator.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]