version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: news_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: news#123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - news_aggregator_net

volumes:
  mysql_data:

networks:
  news_aggregator_net:
    driver: bridge